### PR TITLE
Bug add birthday change constraint

### LINKED ISSUE #520: Add birthday change constraint for checked in users to edit profile
The frontend only uses the `users/current/profile` call, but the api exposes another endpoint which does not have the check for limiting birthday changes when a user is checked in.

https://github.com/AreaFiftyLAN/lancie-api/commit/378258b3c4ada8d2c776ea50e05afc48641de68a#diff-69bbd75df2595c3791120aea66696788R107

### PR DESCRIPTION
**Pull request by julian9499**
fixes #520  
The issue was that the function compared date objects instead of the dates as string. Which resulted in the tests working since we used the same object, but the real life requests not. This has been solved in this pull request. The function has also been put in a separate method which allows the protection of all profile edit paths.

### CODE REVIEW

File: src/main/java/ch/wisv/areafiftylan/users/controller/UserProfileRestController.java [hunk 1]
```diff
@@ -48,19 +48,29 @@
...
+            return true;
+        }
+
+        LocalDate currentBirthday = user.getProfile().getBirthday();
+        boolean isDateChanged = !currentBirthday.toString().equals(input.getBirthday().toString());
+
+        // If rfidLinks are present and the date is changed then return an error
+        if (isDateChanged) {
+            return false;
+        }
```
Comment (skamoen) [inline src/main/java/ch/wisv/areafiftylan/users/controller/UserProfileRestController.java]: You can inline all these variables

File: src/main/java/ch/wisv/areafiftylan/users/controller/UserProfileRestController.java [hunk 2]
```diff
@@ -48,19 +48,29 @@
...
-        User user = userService.addProfile(userId, input);
+    private boolean checkAllowedToEditProfile(User user, ProfileDTO input) {
+        boolean isUserCheckedIn = rfidService.isOwnerLinked(user.getEmail());
+
+        if (!isUserCheckedIn) {
+            return true;
+        }
+
+        LocalDate currentBirthday = user.getProfile().getBirthday();
+        boolean isDateChanged = !currentBirthday.toString().equals(input.getBirthday().toString());
```
Comment (skamoen) [inline src/main/java/ch/wisv/areafiftylan/users/controller/UserProfileRestController.java]: Why would you do an equals on the `toString()` methods and not just the objects itself?

File: src/main/java/ch/wisv/areafiftylan/users/controller/UserProfileRestController.java [hunk 3]
```diff
@@ -48,19 +48,29 @@
...
+     * @return boolean whether they are allowed to edit their profile
      */
-    @PreAuthorize("@currentUserServiceImpl.canAccessUser(principal, #userId)")
-    @PostMapping("/{userId}/profile")
-    public ResponseEntity<?> addProfile(@PathVariable Long userId, @Validated @RequestBody ProfileDTO input) {
-        User user = userService.addProfile(userId, input);
+    private boolean checkAllowedToEditProfile(User user, ProfileDTO input) {
+        boolean isUserCheckedIn = rfidService.isOwnerLinked(user.getEmail());
+
+        if (!isUserCheckedIn) {
```
Comment (skamoen) [inline src/main/java/ch/wisv/areafiftylan/users/controller/UserProfileRestController.java]: Just inline this variable

File: src/test/java/ch/wisv/areafiftylan/integration/UserRestIntegrationTest.java [hunk 4]
```diff
@@ -25,9 +25,11 @@
 import io.restassured.http.ContentType;
 import io.restassured.http.Header;
 import org.apache.http.HttpStatus;
+import org.apache.tomcat.jni.Local;
```
Comment (skamoen) [inline src/test/java/ch/wisv/areafiftylan/integration/UserRestIntegrationTest.java]: What's this?

Comment (julian9499) [reply src/test/java/ch/wisv/areafiftylan/integration/UserRestIntegrationTest.java]: I don't know. Probably a wrong import it was unused. Removed it!

File: src/main/java/ch/wisv/areafiftylan/users/controller/UserProfileRestController.java (hunk 3 above)
Comment (julian9499) [reply src/main/java/ch/wisv/areafiftylan/users/controller/UserProfileRestController.java]: Done!

File: src/main/java/ch/wisv/areafiftylan/users/controller/UserProfileRestController.java (hunk 2 above)
Comment (julian9499) [reply src/main/java/ch/wisv/areafiftylan/users/controller/UserProfileRestController.java]: Removed it and changed it to use the equals method

File: src/main/java/ch/wisv/areafiftylan/users/controller/UserProfileRestController.java (hunk 1 above)
Comment (julian9499) [reply src/main/java/ch/wisv/areafiftylan/users/controller/UserProfileRestController.java]: Done!

File: src/main/java/ch/wisv/areafiftylan/users/model/Profile.java [hunk 5]
```diff
@@ -82,4 +82,8 @@ public void setAllFields(String firstName, String lastName, String displayName,
         this.phoneNumber = phoneNumber;
         this.notes = notes;
     }
+
+    public void setBirthday(LocalDate birthday){
```
Comment (Fastjur) [inline src/main/java/ch/wisv/areafiftylan/users/model/Profile.java]: Can use lombok for getters and setters

File: src/main/java/ch/wisv/areafiftylan/users/model/User.java [hunk 6]
```diff
@@ -100,6 +101,7 @@ public String getPassword() {
 
     public void resetProfile() {
         this.profile = new Profile();
+        this.profile.setBirthday(LocalDate.now());
```
Comment (Fastjur) [inline src/main/java/ch/wisv/areafiftylan/users/model/User.java]: If we reset a profile, should we set the birthdate to now, or to undefined/null ?

It would make more sense to clear it instead of having an arbitrary date filled in.
If that raises errors in the alcohol check, just check for null first.

Comment (julian9499) [reply src/main/java/ch/wisv/areafiftylan/users/model/User.java]: The profile has @nonNull tho

File: src/main/java/ch/wisv/areafiftylan/users/model/Profile.java (hunk 5 above)
Comment (julian9499) [reply src/main/java/ch/wisv/areafiftylan/users/model/Profile.java]: done!

File: src/main/java/ch/wisv/areafiftylan/users/model/User.java (hunk 6 above)
Comment (julian9499) [reply src/main/java/ch/wisv/areafiftylan/users/model/User.java]: I will fill in a arbritrary date

Comment (Fastjur) [reply src/main/java/ch/wisv/areafiftylan/users/model/User.java]: Is it not possible for someone to not have a birthdate then? What about the case where ticket transfers occur?

Comment (julian9499) [reply src/main/java/ch/wisv/areafiftylan/users/model/User.java]: I really don't know enough about the ticket transfers to answer this

File: src/main/java/ch/wisv/areafiftylan/users/controller/UserProfileRestController.java [hunk 7]
```diff
@@ -77,22 +78,28 @@
...
-        LocalDate currentBirthday = user.getProfile().getBirthday();
-        boolean isDateChanged = currentBirthday != input.getBirthday();
-
-        // If rfidLinks are present and the date is changed then return an error
-        if (isDateChanged) {
+        if (checkAllowedToEditProfile(user, input)) {
+            User changedUser = userService.addProfile(user.getId(), input);
+            return createResponseEntity(HttpStatus.OK, "Profile successfully changed", changedUser.getProfile());
+        } else {
             return createResponseEntity(HttpStatus.BAD_REQUEST, "Unable to change date during event", user.getProfile());
```
Comment (martijnjanssen) [inline src/main/java/ch/wisv/areafiftylan/users/controller/UserProfileRestController.java]: Not permitted maybe? The request itself is valid.

File: src/main/java/ch/wisv/areafiftylan/users/controller/UserProfileRestController.java [hunk 8]
```diff
@@ -77,22 +78,28 @@
...
-        if (!isUserCheckedIn) {
-            return this.addProfile(user.getId(), input);
-        }
-
-        LocalDate currentBirthday = user.getProfile().getBirthday();
-        boolean isDateChanged = currentBirthday != input.getBirthday();
-
-        // If rfidLinks are present and the date is changed then return an error
-        if (isDateChanged) {
+        if (checkAllowedToEditProfile(user, input)) {
```
Comment (martijnjanssen) [inline src/main/java/ch/wisv/areafiftylan/users/controller/UserProfileRestController.java]: Just allowedToEditProfile?

File: src/main/java/ch/wisv/areafiftylan/users/model/User.java [hunk 9]
```diff
@@ -100,6 +101,7 @@ public String getPassword() {
 
     public void resetProfile() {
         this.profile = new Profile();
+        this.profile.setBirthday(LocalDate.parse("2000-01-01"));
```
Comment (martijnjanssen) [inline src/main/java/ch/wisv/areafiftylan/users/model/User.java]: This way you're automatically older than 18 after resetting your profile.

Comment (Fastjur) [reply src/main/java/ch/wisv/areafiftylan/users/model/User.java]: Yes this was my thought. I would not set this to any date tbh. Maybe the birthday should be nullable then?

Comment (Fastjur) [reply src/main/java/ch/wisv/areafiftylan/users/model/User.java]: Maybe localdate.now() makes more sense after all? As @julian9499 implemented initially?

File: src/main/java/ch/wisv/areafiftylan/users/model/Profile.java [hunk 10]
```diff
@@ -31,7 +31,7 @@
 
 @Entity
 @Data
-@NoArgsConstructor
+    @NoArgsConstructor
```
Comment (Fastjur) [inline src/main/java/ch/wisv/areafiftylan/users/model/Profile.java]: Whitespace

Comment (julian9499) [reply src/main/java/ch/wisv/areafiftylan/users/model/Profile.java]: fixed!

File: src/main/java/ch/wisv/areafiftylan/users/controller/UserProfileRestController.java (hunk 7 above)
Comment (julian9499) [reply src/main/java/ch/wisv/areafiftylan/users/controller/UserProfileRestController.java]: Done!

File: src/main/java/ch/wisv/areafiftylan/users/controller/UserProfileRestController.java (hunk 8 above)
Comment (julian9499) [reply src/main/java/ch/wisv/areafiftylan/users/controller/UserProfileRestController.java]: Done!

File: src/main/java/ch/wisv/areafiftylan/users/model/User.java (hunk 9 above)
Comment (julian9499) [reply src/main/java/ch/wisv/areafiftylan/users/model/User.java]: Done that @martijnjanssen is this oke?
